server:
  port: 8082
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/tracker;DB_CLOSE_DELAY=-1
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
  mail:
    host: localhost
    port: 25
    username: contact@wijaa.com
    password: Wijaa&2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: false

tracker:
  cors:
    allowed-origins: 'http://localhost:8082,http://localhost:4200'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  mail: # specific Wijja mail property, for standard properties see MailProperties
    from: contact@tracker.com
    base-url: http://localhost:4200


camunda:
  bpm:
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: false
      deploy-changed-only: true
      resume-previous-versions: true
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false
    database:
      type: h2